{% set name = "curl-cffi" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curl_cffi-{{ version }}.tar.gz
  sha256: 0b21f39980bce3fb5aeea8d64d76bd465825c54a45e2933ca4df5ec0f041ba49

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - wheel
    - setuptools
    - cffi >=1.12.0
    - pip
  run:
    - python
    - cffi >=1.12.0
    - certifi >=2024.2.2

test:
  imports:
    - curl_cffi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lexiforest/curl_cffi
  summary: libcurl ffi bindings for Python, with impersonation support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
